import FileGrid from "./FileGrid";
import type { FileItem } from "./FileGrid";

interface Props {
  onOpenFile: (f: FileItem) => void;
}

const POSTS = [
  {
    name: "Building Scalable REST APIs",
    ext: "TXT",
    text: [
      "Building Scalable REST APIs with Node.js",
      "━".repeat(50),
      "",
      "Date        Sep 10, 2026",
      "Read time   6 min",
      "Tags        Node.js · API · Backend",
      "",
      "OVERVIEW",
      "─".repeat(50),
      "A deep dive into designing APIs that hold up under",
      "load — covering rate limiting, caching strategies,",
      "and clean error handling.",
      "",
      "KEY TOPICS",
      "─".repeat(50),
      "  • Rate limiting strategies (token bucket, sliding window)",
      "  • Response caching with Redis",
      "  • Structured error handling and status codes",
      "  • Request validation with Zod",
      "  • Logging and observability",
      "",
      "TAKEAWAYS",
      "─".repeat(50),
      "Good API design is mostly about predictability.",
      "Make errors descriptive, responses consistent,",
      "and always think about what happens under load.",
    ].join("\n"),
  },
  {
    name: "Lessons from the App Router",
    ext: "TXT",
    text: [
      "Lessons from the Next.js App Router",
      "━".repeat(50),
      "",
      "Date        Aug 22, 2026",
      "Read time   5 min",
      "Tags        Next.js · React · Frontend",
      "",
      "OVERVIEW",
      "─".repeat(50),
      "After shipping several projects with the App Router,",
      "here are the patterns that stuck and the gotchas",
      "worth knowing about.",
      "",
      "KEY TOPICS",
      "─".repeat(50),
      "  • Server vs. client components — where to draw the line",
      "  • Parallel routes and intercepting routes",
      "  • Data fetching patterns with async components",
      "  • Caching behaviour and revalidation",
      "",
      "TAKEAWAYS",
      "─".repeat(50),
      "The App Router rewards you for thinking in components",
      "that do one thing. Keep client components at the leaves",
      "of your tree and fetch data as close to where you",
      "need it as possible.",
    ].join("\n"),
  },
  {
    name: "TypeScript Tips",
    ext: "TXT",
    text: [
      "TypeScript Tips I Wish I Knew Earlier",
      "━".repeat(50),
      "",
      "Date        Jul 14, 2026",
      "Read time   4 min",
      "Tags        TypeScript",
      "",
      "OVERVIEW",
      "─".repeat(50),
      "Practical utility types, discriminated unions, and",
      "a few patterns that cut boilerplate without",
      "sacrificing safety.",
      "",
      "KEY TOPICS",
      "─".repeat(50),
      "  • Discriminated unions for state machines",
      "  • Template literal types",
      "  • Infer keyword in conditional types",
      "  • Satisfies operator",
      "  • const assertions",
      "",
      "TAKEAWAYS",
      "─".repeat(50),
      "TypeScript's type system is much more powerful than",
      "most people use. Learning a few advanced patterns",
      "pays dividends across every project.",
    ].join("\n"),
  },
  {
    name: "PostgreSQL Performance",
    ext: "TXT",
    text: [
      "PostgreSQL Performance for Developers",
      "━".repeat(50),
      "",
      "Date        Jun 3, 2026",
      "Read time   7 min",
      "Tags        PostgreSQL · Database · Backend",
      "",
      "OVERVIEW",
      "─".repeat(50),
      "Indexing strategies, query planning, and connection",
      "pooling — the parts of Postgres that make the",
      "biggest difference in production.",
      "",
      "KEY TOPICS",
      "─".repeat(50),
      "  • B-tree vs. GIN vs. BRIN indexes",
      "  • Reading EXPLAIN ANALYZE output",
      "  • N+1 query patterns and how to avoid them",
      "  • Connection pooling with PgBouncer",
      "  • Vacuuming and table bloat",
      "",
      "TAKEAWAYS",
      "─".repeat(50),
      "Most Postgres performance issues come down to missing",
      "indexes or misunderstood query patterns. Start with",
      "EXPLAIN ANALYZE before reaching for anything else.",
    ].join("\n"),
  },
];

export default function BlogContent({ onOpenFile }: Props) {
  return <FileGrid files={POSTS} label="posts" onOpenFile={onOpenFile} />;
}
