import FileGrid from './FileGrid'
import type { FileItem } from './FileGrid'

interface Props { onOpenFile: (f: FileItem) => void }

const FILES: FileItem[] = [
  {
    name: 'Dev Setup',
    text: [
      'My Development Setup',
      '━'.repeat(55),
      '',
      'OS              Windows 11 + WSL2 (Ubuntu)',
      'Editor          VS Code + Cursor',
      'Terminal        Windows Terminal / zsh',
      'Browser         Chrome (dev) / Edge (work)',
      '',
      'TOOLS',
      '─'.repeat(55),
      'Version Control   Git + GitHub',
      'Package Manager   pnpm',
      'DB Client         TablePlus',
      'API Testing       Bruno',
      'Design            Figma',
      '',
      'VS CODE EXTENSIONS',
      '─'.repeat(55),
      '  • Tailwind CSS IntelliSense',
      '  • Prisma',
      '  • ESLint + Prettier',
      '  • GitLens',
      '  • Thunder Client',
      '  • GitHub Copilot',
    ].join('\n'),
  },
  {
    name: 'Reading List',
    text: [
      'Reading List — Books & Resources',
      '━'.repeat(55),
      '',
      'CURRENTLY READING',
      '─'.repeat(55),
      '  • The Pragmatic Programmer — Hunt & Thomas',
      '  • Designing Data-Intensive Applications — Kleppmann',
      '',
      'WANT TO READ',
      '─'.repeat(55),
      '  • Clean Architecture — Robert C. Martin',
      '  • System Design Interview — Alex Xu',
      '  • The Staff Engineer\'s Path — Tanya Reilly',
      '',
      'COMPLETED',
      '─'.repeat(55),
      '  • You Don\'t Know JS — Kyle Simpson',
      '  • JavaScript: The Good Parts — Crockford',
      '  • CSS: The Definitive Guide — Meyer',
    ].join('\n'),
  },
  {
    name: 'Goals 2026',
    text: [
      'Goals — 2026',
      '━'.repeat(55),
      '',
      'TECHNICAL',
      '─'.repeat(55),
      '  [x] Ship M-Pesa Finance Tracker as PWA',
      '  [ ] Launch Restaurant Engine beta',
      '  [ ] Learn Rust (basics)',
      '  [ ] Contribute to an open-source project',
      '  [ ] Get AWS Solutions Architect cert',
      '',
      'CAREER',
      '─'.repeat(55),
      '  [ ] Land a fullstack role at a product company',
      '  [ ] Build in public — share more on LinkedIn',
      '  [x] Keep showing up and shipping things',
      '',
      'PERSONAL',
      '─'.repeat(55),
      '  [ ] Read 12 books this year',
      '  [ ] Actually use the gym membership',
      '  [ ] Learn to cook one (1) proper meal',
    ].join('\n'),
  },
  {
    name: 'Nairobi Tech Scene',
    text: [
      'The Nairobi Tech Scene — Notes',
      '━'.repeat(55),
      '',
      'Nairobi is genuinely one of the best cities in',
      'Africa to be a developer right now. The ecosystem',
      'is growing fast and the talent is world-class.',
      '',
      'NOTABLE COMPANIES',
      '─'.repeat(55),
      '  • Safaricom — M-Pesa, the gold standard of fintech',
      '  • Andela — remote engineering talent platform',
      '  • Twiga Foods — agri-supply chain tech',
      '  • Africa\'s Talking — telco APIs for Africa',
      '  • BRCK — hardware + connectivity',
      '',
      'COMMUNITIES',
      '─'.repeat(55),
      '  • Nairobi Dev Community (NairobiDev)',
      '  • iHub — Africa\'s first tech hub',
      '  • Google Developer Groups Nairobi',
      '  • PyNairobi',
      '',
      'If you\'re hiring in Nairobi — you should be.',
      'The talent is here.',
    ].join('\n'),
  },
]

export default function DocumentsContent({ onOpenFile }: Props) {
  return <FileGrid files={FILES} label="documents" onOpenFile={onOpenFile} />
}
